### In HW 4 we will use we will explore statistical properties of data sets.

### Warning : You do not need to solve this homework with pandas, numpy or anyother library. 
### you can get numpy arrays and do your work on numpy and stats libraries.

for pandas do a tutorial first to understand the indexing 
https://pandas.pydata.org/pandas-docs/stable/getting_started/tutorials.html

#### 1) Car data has information about car makes, models sold in India

In [9]:
import pandas as pd
from datetime import datetime as dt
from scipy import stats
cars = pd.read_csv("data/cars_v1.csv", encoding = "ISO-8859-1")
print(cars.head(10)) # check the first ten rows

#Find mean of price
cars.Price.mean()
cars.Mileage.median()
#cars.groupby('Make') : Finish the code
cars.groupby('Make').Mileage.mean().reset_index()
a = 1

                       Make                                        Model  \
0       Ashok Leyland Stile        Ashok Leyland Stile LE 8-STR (Diesel)
1       Ashok Leyland Stile        Ashok Leyland Stile LS 8-STR (Diesel)
2       Ashok Leyland Stile        Ashok Leyland Stile LX 8-STR (Diesel)
3       Ashok Leyland Stile        Ashok Leyland Stile LS 7-STR (Diesel)
4       Ashok Leyland Stile  Ashok Leyland Stile LS 7-STR Alloy (Diesel)
5       Ashok Leyland Stile        Ashok Leyland Stile LX 7-STR (Diesel)
6       Ashok Leyland Stile  Ashok Leyland Stile LX 7-STR Alloy (Diesel)
7       Aston Martin Rapide            Aston Martin Rapide LUXE (Petrol)
8     Aston Martin Rapide S               Aston Martin Rapide S (Petrol)
9  Aston Martin V12 Vantage      Aston Martin V12 Vantage Coupe (Petrol)

   Price   Type   ABS  BootSpace    GearType AirBag  Engine  FuelCapacity  \
0    750    MPV    No      500.0      Manual     No  1461.0          50.0
1    800    MPV    No      500.0      Manual     No  1461.0          50.0
2    830    MPV    No      500.0      Manual     No  1461.0          50.0
3    850    MPV    No      500.0      Manual     No  1461.0          50.0
4    880    MPV    No      500.0      Manual     No  1461.0          50.0
5    900    MPV    No      500.0      Manual     No  1461.0          50.0
6    930    MPV    No      500.0      Manual     No  1461.0          50.0
7  35000  Sedan   Yes      300.0   Automatic    Yes  5935.0          90.5
8  44000  Sedan   Yes        NaN   Automatic    Yes  5935.0          90.0
9  35000  Coupe   Yes      300.0   Automatic    Yes  5935.0          80.0

   Mileage
0     20.7
1     20.7
2     20.7
3     20.7
4     20.7
5     20.7
6     20.7
7      7.0
8     11.9
9      9.0

#### 1a) Describe data with mean, std, modes, median, quantiles, max

              Price    BootSpace       Engine  FuelCapacity     Mileage
count    833.000000   654.000000   826.000000    833.000000  662.000000
mean    3159.495798   409.536697  1900.533898     51.341693   17.480408
std     6272.519112   175.351525  1065.149758     17.643132    4.584628
min      199.000000    80.000000   624.000000      0.000000    5.000000
25%      619.000000   256.000000  1248.000000     42.000000   14.000000
50%      880.000000   418.000000  1497.000000     50.000000   17.985000
75%     2329.000000   500.000000  2179.000000     64.000000   20.700000
max    50000.000000  1000.000000  6592.000000    120.000000   30.000000

In [17]:
cars.isnull().sum() # 171 cars have no Mileage information remove them.
# like numpy you use boolean indexing

Make              0
Model             0
Price             0
Type              0
ABS              16
BootSpace       179
GearType         16
AirBag           21
Engine            7
FuelCapacity      0
Mileage         171
dtype: int64

#### 1b) Remove the data  which does not have mileage information (like numpy you use boolean indexing)

- cars2 is cars with mileage information
- do not forget to make a copy into cars2
- also reset the Index so index is continuos

,index,Make,Model,Price,Type,ABS,BootSpace,GearType,AirBag,Engine,FuelCapacity,Mileage
0,0,Ashok Leyland Stile,Ashok Leyland Stile LE 8-STR (Diesel),750,MPV,No,500.0,Manual,No,1461.0,50.0,20.70
1,1,Ashok Leyland Stile,Ashok Leyland Stile LS 8-STR (Diesel),800,MPV,No,500.0,Manual,No,1461.0,50.0,20.70
2,2,Ashok Leyland Stile,Ashok Leyland Stile LX 8-STR (Diesel),830,MPV,No,500.0,Manual,No,1461.0,50.0,20.70
3,3,Ashok Leyland Stile,Ashok Leyland Stile LS 7-STR (Diesel),850,MPV,No,500.0,Manual,No,1461.0,50.0,20.70
4,4,Ashok Leyland Stile,Ashok Leyland Stile LS 7-STR Alloy (Diesel),880,MPV,No,500.0,Manual,No,1461.0,50.0,20.70
5,5,Ashok Leyland Stile,Ashok Leyland Stile LX 7-STR (Diesel),900,MPV,No,500.0,Manual,No,1461.0,50.0,20.70
6,6,Ashok Leyland Stile,Ashok Leyland Stile LX 7-STR Alloy (Diesel),930,MPV,No,500.0,Manual,No,1461.0,50.0,20.70
7,7,Aston Martin Rapide,Aston Martin Rapide LUXE (Petrol),35000,Sedan,Yes,300.0,Automatic,Yes,5935.0,90.5,7.00
8,8,Aston Martin Rapide S,Aston Martin Rapide S (Petrol),44000,Sedan,Yes,NaN,Automatic,Yes,5935.0,90.0,11.90
9,9,Aston Martin V12 Vantage,Aston Martin V12 Vantage Coupe (Petrol),35000,Coupe,Yes,300.0,Automatic,Yes,5935.0,80.0,9.00
10,10,Aston Martin V8 Vantage,Aston Martin V8 Vantage Coupe (Petrol),13500,Coupe,Yes,300.0,Automatic,Yes,4735.0,80.0,5.00
11,11,Aston Martin V8 Vantage,Aston Martin V8 Vantage S Coupe (Petrol),25500,Coupe,Yes,300.0,Automatic,Yes,4735.0,80.0,5.00
12,12,Aston Martin V8 Vantage,Aston Martin V8 Vantage Roadster (Petrol),27000,Coupe,Yes,300.0,Automatic,Yes,4735.0,80.0,5.00
13,13,Aston Martin Vanquish,Aston Martin Vanquish V12 (Petrol),38500,Sedan,Yes,240.0,Automatic,Yes,5935.0,78.0,8.00
14,14,Audi A3 Cabriolet,Audi A3 Attraction 35 TDI (Diesel),2295,Sedan,Yes,NaN,NaN,NaN,1968.0,50.0,20.38
15,15,Audi A3 Cabriolet,Audi A3 Premium 35 TDI (Diesel),2595,Sedan,Yes,NaN,NaN,NaN,1968.0,50.0,20.38
16,16,Audi A3 Cabriolet,Audi A3 Premium Plus 40 TFSI (Petrol),2895,Sedan,Yes,NaN,Automatic,Yes,1798.0,50.0,16.60
17,17,Audi A3 Cabriolet,Audi A3 Premium Plus 35 TDI (Diesel),2995,Sedan,Yes,NaN,NaN,NaN,1968.0,50.0,20.38
18,18,Audi A3 Cabriolet,Audi A3 Technology 35 TDI (Diesel),3266,Sedan,Yes,NaN,NaN,NaN,1968.0,50.0,20.38
19,19,Audi A3 Cabriolet,Audi A3 Cabriolet (Petrol),4475,Convertible,Yes,320.0,Automatic,Yes,1798.0,63.0,17.00
20,20,Audi A4,Audi A4 2.0 TDI (Diesel),2899,Sedan,Yes,480.0,Automatic,Yes,1968.0,61.0,16.55
21,21,Audi A4,Audi A4 1.8 TFSI (Petrol),3058,Sedan,Yes,480.0,Automatic,Yes,1798.0,63.0,15.64
22,22,Audi A4,Audi A4 2.0 TDI Multitronic (Diesel),3361,Sedan,Yes,480.0,Automatic,Yes,1968.0,63.0,16.55
23,23,Audi A4,Audi A4 S4 3.0 TFSI quattro (Petrol),5235,Sedan,Yes,480.0,Automatic,Yes,2995.0,61.0,10.34
24,24,Audi A4,Audi A4 3.0 TDI Quattro (Diesel),5471,Sedan,Yes,480.0,Automatic,Yes,2967.0,61.0,14.94
25,25,Audi A6,Audi A6 2.0 TDI (Diesel),4356,Sedan,Yes,535.0,Automatic,Yes,1968.0,65.0,17.68
26,26,Audi A6,Audi A6 3.0 TFSI quattro (Petrol),4700,Sedan,Yes,535.0,Automatic,Yes,1984.0,65.0,13.53
27,27,Audi A6,Audi A6 3.0 TDI quattro (Diesel),5424,Sedan,Yes,535.0,Automatic,Yes,2967.0,75.0,14.57
28,28,Audi A7,Audi A7 Sportback 3.0 TDI (Diesel),8588,Sedan,Yes,535.0,Automatic,Yes,2967.0,65.0,14.40
29,29,Audi A8 L,Audi A8 L 3.0 TDI quattro (Diesel),10700,Sedan,Yes,500.0,Automatic,Yes,2967.0,90.0,15.50
...,...,...,...,...,...,...,...,...,...,...,...,...
632,800,Volkswagen Passat,Volkswagen Passat Highline DSG (Diesel),2726,Sedan,Yes,565.0,Automatic,Yes,1968.0,70.0,18.78
633,801,Volkswagen Polo,Volkswagen Polo 1.2L Trendline (Petrol),535,Hatchback,No,280.0,Manual,Yes,1198.0,45.0,16.47
634,802,Volkswagen Polo,Volkswagen Polo 1.2L Comfortline (Petrol),597,Hatchback,Yes,280.0,Manual,Yes,1198.0,45.0,16.47
635,803,Volkswagen Polo,Volkswagen Polo 1.2L Highline (Petrol),649,Hatchback,Yes,280.0,Automatic,Yes,1198.0,45.0,16.47
636,804,Volkswagen Polo,Volkswagen Polo 1.5L Trendline (Diesel),670,Hatchback,No,280.0,Manual,Yes,1498.0,45.0,20.14
637,805,Volkswagen Polo,Volkswagen Polo 1.5L Comfortline (Diesel),733,Hatchback,Yes,280.0,Manual,Yes,1498.0,45.0,20.14
638,806,Volkswagen Polo,Volkswagen Polo 1.5L Highline (Diesel),784,Hatchback,Yes,280.0,Automatic,Yes,1498.0,45.0,20.14
639,807,Volkswagen Polo GT,Volkswagen Polo GT TDI (Diesel),800,Hatchback,Yes,250.0,Automatic,Yes,1598.0,45.0,19.70
640,808,Volkswagen Polo GT,Volkswagen Polo GT TSI (Petrol),850,Hatchback,Yes,250.0,Automatic,Yes,1197.0,45.0,17.20
641,810,Volkswagen Up,Volkswagen Up ï¿½ï¿½ï¿½ Expected Specification,360,Hatchback,Yes,220.0,Manual,Yes,1199.0,45.0,21.00
642,811,Volkswagen Vento,Volkswagen Vento Trendline (Petrol),785,Sedan,No,494.0,Manual,No,1598.0,55.0,16.09
643,812,Volkswagen Vento,Volkswagen Vento Comfortline MT (Petrol),867,Sedan,Yes,494.0,Automatic,Yes,1598.0,55.0,16.09
644,813,Volkswagen Vento,Volkswagen Vento Trendline (Diesel),910,Sedan,No,494.0,Manual,Yes,1498.0,55.0,20.64
645,814,Volkswagen Vento,Volkswagen Vento Highline MT (Petrol),942,Sedan,Yes,NaN,Automatic,Yes,1598.0,55.0,16.09
646,815,Volkswagen Vento,Volkswagen Vento Comfortline AT (Petrol),987,Sedan,Yes,494.0,Manual,Yes,1197.0,55.0,18.19
647,816,Volkswagen Vento,Volkswagen Vento Comfortline MT (Diesel),992,Sedan,Yes,494.0,Manual,Yes,1498.0,55.0,20.64
648,817,Volkswagen Vento,Volkswagen Vento Highline AT (Petrol),1062,Sedan,Yes,494.0,Automatic,Yes,1197.0,55.0,18.19
649,818,Volkswagen Vento,Volkswagen Vento Highline MT (Diesel),1067,Sedan,Yes,494.0,Manual,Yes,1498.0,55.0,20.64
650,819,Volkswagen Vento,Volkswagen Vento Comfortline AT (Diesel),1112,Sedan,Yes,494.0,Automatic,Yes,1498.0,55.0,21.50
651,820,Volkswagen Vento,Volkswagen Vento Highline AT (Diesel),1187,Sedan,Yes,494.0,Manual,Yes,1498.0,55.0,21.50
652,822,Volvo S60,Volvo S60 Summum D4 (Diesel),3390,Sedan,Yes,339.0,Automatic,Yes,1984.0,67.5,18.50
653,823,Volvo S60,Volvo S60 Summum D5 (Diesel),3690,Sedan,Yes,339.0,Automatic,Yes,2400.0,67.5,20.40
654,824,Volvo S60,Volvo S60 T6,4200,Sedan,Yes,380.0,Automatic,Yes,1969.0,67.0,18.50
655,825,Volvo S80,Volvo S80 Summum D4 (Diesel),4135,Sedan,Yes,480.0,Automatic,Yes,1984.0,70.0,16.66
656,827,Volvo V40,Volvo V40 D3 Kinetic (Diesel),2475,Hatchback,Yes,335.0,Automatic,Yes,1969.0,62.0,27.80
657,828,Volvo V40,Volvo V40 D3 R-Design (Diesel),2770,Hatchback,Yes,324.0,Automatic,Yes,1984.0,62.0,27.80
658,829,Volvo V40 Cross Country,Volvo V40 D3 Cross Country (Diesel),3180,Hatchback,Yes,335.0,Automatic,Yes,1984.0,60.0,16.80
659,830,Volvo V40 Cross Country,Volvo V40 T4 Cross Country (Petrol),3240,Hatchback,Yes,324.0,Automatic,Yes,1596.0,50.0,16.00
660,831,Volvo XC90,Volvo XC 90 D5 Momentum(Diesel),6490,SUV,Yes,NaN,Automatic,Yes,1969.0,68.0,11.10
661,832,Volvo XC90,Volvo XC 90 D5 Inscription(Diesel),7790,SUV,Yes,NaN,Automatic,Yes,1969.0,68.0,11.10

#### 1c) Display the covariance information for cars2 
What can you say covariance of engine size and mileage?

,Price,BootSpace,Engine,FuelCapacity,Mileage
Price,3.630874e+07,179445.925571,5.470702e+06,59665.561959,-14644.543057
BootSpace,1.794459e+05,27132.658624,5.697838e+04,1333.667881,-252.201370
Engine,5.470702e+06,56978.379702,1.150887e+06,13678.109282,-3442.585057
FuelCapacity,5.966556e+04,1333.667881,1.367811e+04,261.872270,-49.155196
Mileage,-1.464454e+04,-252.201370,-3.442585e+03,-49.155196,21.018811

####  1d) Display the correlations for attributes 
Which attributes are strongly (>0.5 or <-0.5) correlated? Which two variables have maximum correlation or anti-correlation

                 Price  BootSpace    Engine  FuelCapacity   Mileage
Price         1.000000   0.183640  0.844677      0.611890 -0.530110
BootSpace     0.183640   1.000000  0.313696      0.485724 -0.329319
Engine        0.844677   0.313696  1.000000      0.793774 -0.698500
FuelCapacity  0.611890   0.485724  0.793774      1.000000 -0.662553
Mileage      -0.530110  -0.329319 -0.698500     -0.662553  1.000000

#### Which two variables have maximum correlation or anti-correlation? Do not count self-correlations
Plot scatter plots for those attributes

#### 1d) What is the mean fuel mileage for Automatic cars? 
 What is the mean fuel mileage for Manual Hatchbacks?
 
- Be carefull that some attributes have spaces in the names. cars2.GearType==' Automatic'

Mean automatic:  15.745466237942123
Mean manual:  19.112636363636362

#### 1e) What is the mean fuel mileage for TypeSedan cars?
 What is the mean fuel mileage for Type Hatchbacks?

,Make,Model,Price,Type,ABS,BootSpace,GearType,AirBag,Engine,FuelCapacity,Mileage
7,Aston Martin Rapide,Aston Martin Rapide LUXE (Petrol),35000,Sedan,Yes,300.0,Automatic,Yes,5935.0,90.5,7.00
8,Aston Martin Rapide S,Aston Martin Rapide S (Petrol),44000,Sedan,Yes,NaN,Automatic,Yes,5935.0,90.0,11.90
13,Aston Martin Vanquish,Aston Martin Vanquish V12 (Petrol),38500,Sedan,Yes,240.0,Automatic,Yes,5935.0,78.0,8.00
14,Audi A3 Cabriolet,Audi A3 Attraction 35 TDI (Diesel),2295,Sedan,Yes,NaN,NaN,NaN,1968.0,50.0,20.38
15,Audi A3 Cabriolet,Audi A3 Premium 35 TDI (Diesel),2595,Sedan,Yes,NaN,NaN,NaN,1968.0,50.0,20.38
16,Audi A3 Cabriolet,Audi A3 Premium Plus 40 TFSI (Petrol),2895,Sedan,Yes,NaN,Automatic,Yes,1798.0,50.0,16.60
17,Audi A3 Cabriolet,Audi A3 Premium Plus 35 TDI (Diesel),2995,Sedan,Yes,NaN,NaN,NaN,1968.0,50.0,20.38
18,Audi A3 Cabriolet,Audi A3 Technology 35 TDI (Diesel),3266,Sedan,Yes,NaN,NaN,NaN,1968.0,50.0,20.38
20,Audi A4,Audi A4 2.0 TDI (Diesel),2899,Sedan,Yes,480.0,Automatic,Yes,1968.0,61.0,16.55
21,Audi A4,Audi A4 1.8 TFSI (Petrol),3058,Sedan,Yes,480.0,Automatic,Yes,1798.0,63.0,15.64

Mean sedan:  18.065371900826445
Mean hb:  20.507878787878784

#### 1f) 1. Hypothesis :  Automatic cars mileage is lower than Manual cars. Do the t-tests on data to show if the mean difference is significant

#### 1g) 2. Hypothesis :  Sedan cars mileage is lower than Hb cars. Do the t-tests on data to show if the mean difference is significant

#### 1h) Above t-tests assume normal distribution of sample. 
Does automatic car mileage have normal distribution?
Does manual car mileage have normal distribution?

Does sedan car mileage have normal distribution?
Does hb car mileage have normal distribution?